name: CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    env:
      CI: false
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm install --legacy-peer-deps
    - name: Build project
      run: npm run build
  configure-git:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Configure git
        run:
          cd ${{ github.workspace }} &&
          git config --global user.name ${{ env.user_name }} &&
          git config --global user.email ${{ env.user_email }} &&
          git remote set-url origin https://${{ env.user_name }}${{ env.github_token }}@github.com/${{ env.repository }}.git
        env:
          user_name: 'tcq1'
          user_email: 'tru.chu.qu@gmail.com'
          github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
          repository: ${{ github.repository }}
  deploy:
    needs: configure-git
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Github Pages
        run: npm run deploy
