name: CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    env:
      CI: false
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm install --legacy-peer-deps
    - name: Build project
      run: npm run build
    - name: Set Git config
      run:
        git config --global user.name ${{ env.user_name }}
        git config --global user.email ${{ user_email }}
      env:
        user_name: 'tcq1'
        user_email: 'tru.chu.qu@gmail.com'
    - name: Set Git remote URL
      run:
        git remote set-url origin https://${{ github_token }}@github.com/${{ repository }}
      env:
        github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
        repository: ${{ github.repository }}
    - name: Deploy to Github Pages
      run: npm run deploy
